services:
  config-gen:
    image: alpine:latest
    container_name: cattiva-config-gen
    volumes:
      - xray-configs:/etc/xray
      - nginx-conf:/etc/nginx/conf.d
      - ./data/acme:/acme
      - ./xray:/templates/xray:ro
      - ./nginx:/templates/nginx:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      - SITE_DOMAIN=${SITE_DOMAIN:?err}
      - ACME_EMAIL=${ACME_EMAIL:?err}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?err}
      - VLESS_UUID=${VLESS_UUID:?err}
      - REALITY_PRIVATE_KEY=${REALITY_PRIVATE_KEY:?err}
      - REALITY_DEST=${REALITY_DEST:-www.apple.com:443}
      - REALITY_SERVER_NAMES=${REALITY_SERVER_NAMES:-www.apple.com, www.icloud.com}
      - REALITY_SHORT_ID=${REALITY_SHORT_ID:-6ba85179e30d4fc2}
      - VMESS_UUID=${VMESS_UUID:?err}
      - VMESS_WS_PATH=${VMESS_WS_PATH:-/proxy/ws}
      - VMESS_SERVER_NAMES=${VMESS_SERVER_NAMES}
    command: ["sh", "/entrypoint.sh"]

  nginx:
    image: nginx:latest
    container_name: cattiva-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/www:ro
      - ./data/acme:/acme
    depends_on:
      config-gen:
        condition: service_completed_successfully
    networks:
      - cattiva

  xray-reality:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-reality
    restart: always
    volumes:
      - xray-configs:/etc/xray:ro
    depends_on:
      config-gen:
        condition: service_completed_successfully
    networks:
      - cattiva

  xray-vmess:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-vmess
    restart: always
    volumes:
      - xray-configs:/etc/xray:ro
    depends_on:
      config-gen:
        condition: service_completed_successfully
    networks:
      - cattiva

networks:
  cattiva:
    driver: bridge

volumes:
  xray-configs:
  nginx-conf:
