services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./data/acme:/acme
      - ./data/traefik:/data
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?err}
      - REALITY_SERVER_NAMES=${REALITY_SERVER_NAMES}
      - VMESS_SERVER_NAMES=${VMESS_SERVER_NAMES}
    networks:
      - cattiva

  xray-reality:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-reality
    restart: always
    volumes:
      - ./xray/reality.json:/etc/xray/config.json:ro
    networks:
      - cattiva

  xray-vmess:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-vmess
    restart: always
    volumes:
      - ./xray/vmess.json:/etc/xray/config.json:ro
      - ./data/certs:/etc/xray/certs:ro
    networks:
      - cattiva

networks:
  cattiva:
    driver: bridge
